FROM node:20.15-bullseye

RUN apt-get update && apt-get install -y \
    curl \
    python2.7 \
    zopfli \
 && ln -sf /usr/bin/python2.7 /usr/local/bin/python \
 && curl -fsSL https://bootstrap.pypa.io/pip/2.7/get-pip.py -o /tmp/get-pip.py \
 && python /tmp/get-pip.py \
 && rm -f /tmp/get-pip.py \
 && rm -rf /var/lib/apt/lists/*
COPY . /site
WORKDIR /site
RUN npm install \
	&& pip install -r requirements.txt \
	&& npx grunt build \
	&& mv bin/templates/about-generated.html bin/about.html \
	&& mv bin/templates/home-generated.html bin/index.html \
	&& mv bin/templates/statistics-generated.html bin/statistics.html

FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /site/bin /usr/share/nginx/html
VOLUME /usr/share/nginx/html/data
