FROM python:2.7

COPY . /site
WORKDIR /site

RUN pip install -r requirements.txt \
    && pip install gunicorn==19.10.0 \
    && echo "/database.db" > .database

ENTRYPOINT ["gunicorn", "-b", "0.0.0.0", "app:app"]

VOLUME "/database.db"
